package com.ryan.conal.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * The port type of the WSDL is an element that is comparable to an interface in Java.
 * 			It defines the type or types of services that are available.
 * 			It is given a unique name (e.g. 'Orders') to identify it in the document.
 * 			Will create Orders.java Interface
 * 
 * 			@WebService(targetNamespace = "http://www.conal.ryan.com/service/Orders/", name = "Orders")
 * 			@XmlSeeAlso({com.ryan.conal.schema.order.ObjectFactory.class})
 * 			@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
 * 			public interface Orders {
 * 
 * 				@WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.conal.ryan.com/service/Orders/ProcessOrderPlacement")
 * 				@WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.conal.ryan.com/schema/Order", partName = "orderInquiryResponse")
 * 				public com.ryan.conal.schema.order.OrderInquiryResponseType processOrderPlacement(
 * 					@WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.conal.ryan.com/schema/Order")
 * 					com.ryan.conal.schema.order.OrderInquiryType orderInquiry
 * 				);
 * 			}
 * 
 * 		
 *
 * This class was generated by Apache CXF 2.7.8
 * 2017-08-10T15:40:55.163-04:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.conal.ryan.com/service/Orders/", name = "Orders")
@XmlSeeAlso({com.ryan.conal.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.conal.ryan.com/service/Orders/ProcessOrderPlacement")
    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.conal.ryan.com/schema/Order", partName = "orderInquiryResponse")
    public com.ryan.conal.schema.order.OrderInquiryResponseType processOrderPlacement(
        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.conal.ryan.com/schema/Order")
        com.ryan.conal.schema.order.OrderInquiryType orderInquiry
    );
}
